name = "drive"
type = "webpack"
workers_dev = true
account_id = "b87997a496f985b46b927b3f24c61de1"
kv_namespaces = [
    { binding = "BUCKET", id = "09b0cf433f394b309d35d1ff3bd0bf39" }
]

[env.staging]
name = "drive-staging"
